version: '2'
services:
    clothes-app:
        image: clothes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://clothes-mysql:3306/clothes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=clothes-elasticsearch:9300
        ports:
            - 8080:8080
    clothes-mysql:
        extends:
            file: mysql.yml
            service: clothes-mysql
    clothes-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: clothes-elasticsearch
